# Generated by Django 2.1.4 on 2019-06-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WjzInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ywid', models.CharField(blank=True, max_length=255, null=True)),
                ('jd', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('money', models.FloatField()),
                ('phone', models.CharField(max_length=128)),
                ('agent', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('begindate', models.CharField(max_length=64)),
                ('enddate', models.CharField(max_length=64)),
                ('validity', models.CharField(blank=True, max_length=128, null=True)),
                ('documenturl', models.TextField(blank=True, null=True)),
                ('managenum', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wjz_info',
                'managed': False,
            },
        ),
    ]
